# Site settings
title: "Nick Thompson"
title_end: " âˆ™ Nick Thompson"
description: > # this means to ignore newlines until "baseurl:"
  Future description for the website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickthompson.guru/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


# Colors (hex)
#colors:
#  primary: "#AB3C47"
#  secondary: "#872F38"
#  dark: "#121011"
#  med: "#574D52"
#  light: "#D1BAC5"
#  text_light: "#FFFFFF"
#  text_dark: "#000000"
  
colors:  #in hex code if not noted else
  primary: "#AB3C47" #"#F70031" 
  secondary: "#872F38" #"#33004D"
  background: "#333333"
  navbar: "#000000"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer: "#111"
  footer_heading: "#ffffff"
  footer_content: "#fff"
